[package]
name = "core-timer"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
