name: Release builds

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: dtolnay/rust-toolchain@stable
      - name: Install deps
        run: |
          cd apps/desktop
          npm i -g pnpm
          pnpm i
      - name: Build
        run: |
          cd apps/desktop
          pnpm build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-bundles
          path: src-tauri/target/release/bundle/**/*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: dtolnay/rust-toolchain@stable
      - name: Install deps
        shell: bash
        run: |
          cd apps/desktop
          npm i -g pnpm
          pnpm i
      - name: Build
        shell: bash
        run: |
          cd apps/desktop
          pnpm build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundles
          path: src-tauri/target/release/bundle/**/*
